---
- name: include secret vars
  include_vars: secret.yml

- name: stat /usr/bin/mackerel-agent
  stat:
    path: /usr/bin/mackerel-agent
  register: mackerel_agent

- name: download mackerel-agent.deb
  get_url:
    url: https://github.com/mackerelio/mackerel-agent/releases/download/v0.72.1/mackerel-agent_0.72.1-1.systemd_armhf.deb
    dest: /tmp
  when:
    - not mackerel_agent.stat.exists

- name: install mackerel-agent.deb
  apt:
    deb: /tmp/mackerel-agent_0.72.1-1.systemd_armhf.deb
  when:
    - not mackerel_agent.stat.exists

- name: setup apikey to mackerel-agent.conf
  lineinfile: dest=/etc/mackerel-agent/mackerel-agent.conf
    line='{{ item.line }}'
    regexp='{{ item.regexp }}'
  with_items:
    - {
        line: 'apikey="{{ mackerel_apikey }}"',
        regexp: '^apikey="{{ mackerel_apikey }}"',
      }
  notify: restart mackerel-agent
