---
- name: include secret vars
  include_vars: secret.yml

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: set /etc/hosts
  replace:
    path: /etc/hosts
    regexp: raspberrypi
    replace: "{{ hostname }}"

- name: add authorized_key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/Tanaka/id_rsa_raspi.pub') }}"

# reduce writing into SD card
- name: mount /tmp as fstmp
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,size=64m,noatime,mode=1777
    state: present
- name: mount /var/tmp as fstmp
  mount:
    path: /var/tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,size=32m,noatime,mode=1777
    state: present

# 'swap' turn off because swap put a strain on SD card.
- name: swapoff
  script: swapoff.sh
  register: result
  changed_when: result.rc == 254
  failed_when: result.rc not in [0, 254]

# disable swap service after reboot
- name: disable swap service
  systemd:
    name: dphys-swapfile
    enabled: no
    state: stopped

- name: copy rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
