on:
  push:
    branches:
      - master
      - develop
name: Ansible Lint
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint check with Ansible
        run: ansible-lint raspi3modelb.yml
